### ISSUE TITLE
Merge labuilding error at JOSM Revision:10169

### ISSUE THREAD

**Issue by maning** [mapbox/auto-tools#6]
This happens when I try to merge where one is a closed way and the other is a relation.

```
{{{
URL:http://josm.openstreetmap.de/svn/trunk
Repository:UUID: 0c6e7542-c601-0410-84e7-c038aed88b3b
Last:Changed Date: 2016-05-03 21:21:04 +0200 (Tue, 03 May 2016)
Build-Date:2016-05-04 01:31:53
Revision:10169
Relative:URL: ^/trunk

Identification: JOSM/1.5 (10169 en) Mac OS X 10.10.5
Memory Usage: 835 MB / 1820 MB (96 MB allocated, but free)
Java version: 1.8.0_60-b27, Oracle Corporation, Java HotSpot(TM) 64-Bit Server VM
VM arguments: [-Djosm.pref=<josm.pref>/]
Dataset consistency test: No problems found

Plugins:
- DirectDownload (32158)
- DirectUpload (32158)
- FastDraw (32158)
- ImageWayPoint (32158)
- ImportImagePlugin (32158)
- Mapillary (32158)
- PicLayer (32158)
- RoadSigns (32177)
- ShapeTools (1000)
- apache-commons (32158)
- apache-http (32158)
- auto_tools (1464021946)
- buildings_tools (32158)
- changesetID (1461665161)
- continuosDownload (44)
- editgpx (32158)
- ejml (32158)
- ext_tools (32158)
- fieldpapers (v0.4.0)
- geochat (32158)
- geotools (31895)
- graphview (32158)
- imagery_offset_db (32158)
- imageryadjust (32158)
- josm-config (1449603193)
- jts (31906)
- log4j (32158)
- mbtiles (v2.0)
- measurement (32158)
- merge-overlap (32158)
- opendata (32158)
- pbf (32158)
- photo_geotagging (32158)
- reltoolbox (32158)
- reverter (32158)
- routing (32158)
- scripting (30722)
- tag2link (31923)
- tageditor (32158)
- terracer (32158)
- todo (29154)
- turnlanes (32158)
- turnrestrictions (32158)
- undelete (32158)
- utilsplugin2 (32158)

Tagging presets:
- https://josm.openstreetmap.de/josmfile?page=Presets/LaneAttributes&zip=1

Map paint styles:
- ${HOME}/osm/version.mapcss
- https://github.com/gmgeo/osmic-josm-style/archive/master.zip
- https://github.com/hotosm/HDM-JOSM-style/archive/master.zip
- https://josm.openstreetmap.de/josmfile?page=Styles/Coloured_buildings&zip=1
- https://josm.openstreetmap.de/josmfile?page=Styles/Lane_and_Road_Attributes&zip=1
- https://josm.openstreetmap.de/josmfile?page=Styles/Lane_features&zip=1
- https://josm.openstreetmap.de/josmfile?page=Styles/Lane_features_ryg&zip=1
- https://josm.openstreetmap.de/josmfile?page=Styles/LessObtrusiveNodes&zip=1
- https://josm.openstreetmap.de/josmfile?page=Styles/Maxspeed&zip=1
- https://josm.openstreetmap.de/josmfile?page=Styles/Sidewalks&zip=1
- https://josm.openstreetmap.de/josmfile?page=Styles/Traffic_signs&zip=1
- https://raw.githubusercontent.com/Andygol/josm-styles/master/created_in_2015.mapcss
- https://raw.githubusercontent.com/species/josm-preset-traffic_sign_direction/master/direction.mapcss

Validator rules:
- https://gist.githubusercontent.com/<user.name>/80414b47cdf160710287bf99e208b552/raw/4d429639e43de18da58d669f595844eb43faf86a/labuilding.mapcss

Last errors/warnings:
- E: Skipping to the next rule, because of an error:
- E: org.openstreetmap.josm.gui.mappaint.mapcss.parsergen.ParseException: Encountered " ":" ": "" at line 3, column 14.
- W: Failed to add https://gist.githubusercontent.com/<user.name>/80414b47cdf160710287bf99e208b552/raw/4d429639e43de18da58d669f595844eb43faf86a/labuilding.mapcss to tag checker
- W: org.openstreetmap.josm.gui.mappaint.mapcss.parsergen.ParseException: Encountered " "}" "} "" at line 6, column 4.
- E: java.lang.NullPointerException

java.lang.NullPointerException
    at java.util.Hashtable.put(Hashtable.java:459)
    at org.openstreetmap.josm.plugins.auto_tools.actions.MergeBuildingsAction.actionPerformed(MergeBuildingsAction.java:67)
    at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
    at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
    at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
    at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
    at javax.swing.AbstractButton.doClick(AbstractButton.java:376)
    at javax.swing.plaf.basic.BasicMenuItemUI.doClick(BasicMenuItemUI.java:833)
    at javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(BasicMenuItemUI.java:877)
    at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)
    at java.awt.Component.processMouseEvent(Component.java:6535)
    at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
    at java.awt.Component.processEvent(Component.java:6300)
    at java.awt.Container.processEvent(Container.java:2236)
    at java.awt.Component.dispatchEventImpl(Component.java:4891)
    at java.awt.Container.dispatchEventImpl(Container.java:2294)
    at java.awt.Component.dispatchEvent(Component.java:4713)
    at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
    at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
    at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
    at java.awt.Container.dispatchEventImpl(Container.java:2280)
    at java.awt.Window.dispatchEventImpl(Window.java:2750)
    at java.awt.Component.dispatchEvent(Component.java:4713)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
    at java.awt.EventQueue.access$500(EventQueue.java:97)
    at java.awt.EventQueue$3.run(EventQueue.java:709)
    at java.awt.EventQueue$3.run(EventQueue.java:703)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
    at java.awt.EventQueue$4.run(EventQueue.java:731)
    at java.awt.EventQueue$4.run(EventQueue.java:729)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
}}}
```

@Rub21

**Comment by Rub21** [comment]
@maning  the  plugin is working for merge just ways, we have to  add new functionality to merger relation-relation and way-relation.
 next week I can back to add the new functionalities .

**Comment by samely** [comment]
@Rub21 @maning  this is already done.
